# Configuration file for AppVeyor CI
configuration: Release

image:
- Visual Studio 2019

# Build and test only once for a pull request.
skip_branch_with_pr: true

environment:
  matrix:
    - QTDIR: C:\Qt\5.13\mingw73_32
      CMAKE_GENERATOR: MinGW Makefiles
      MINGW_PATH: C:\Qt\Tools\mingw730_32
      # https://wiki.qt.io/Qt_5.13_Tools_and_Versions
      # https://www.appveyor.com/docs/windows-images-software/#tools
      OPENSSL_PATH: C:\OpenSSL-v111-Win32\bin
      LIBSSL: libssl-1_1.dll
      LIBCRYPTO: libcrypto-1_1.dll

    - QTDIR: C:\Qt\5.13\mingw73_64
      CMAKE_GENERATOR: MinGW Makefiles
      MINGW_PATH: C:\Qt\Tools\mingw730_64
      OPENSSL_PATH: C:\OpenSSL-v111-Win64\bin
      LIBSSL: libssl-1_1-x64.dll
      LIBCRYPTO: libcrypto-1_1-x64.dll

# Parameters for default build commands (build_script is used instead).
build:

install:
- utils\appveyor\install.bat

before_build:
- utils\appveyor\before_build.bat

build_script:
- utils\appveyor\build_script.bat

after_build:
- utils\appveyor\after_build.bat

artifacts:
- path: 'copyq*.zip'
  name: CopyQ Portable

- path: 'copyq-*-setup.exe'
  name: CopyQ Setup

# Upload test log files.
on_finish:
- ps: Get-ChildItem -recurse -include copyq*.log* | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.
